### ISSUE TITLE
Non-python syntax highlighting disabled

### ISSUE THREAD

**Issue by fonnesbeck** [jupyter/notebook#1439]
In the current `notebook` master running on OS X 10.11.4 (Python 3.5.1), non-Python kernels do not have syntax highlighting enabled. Examples for the R and Julia kernels are depicted below:
## R

![screenshot 2016-05-10 09 06 01](https://cloud.githubusercontent.com/assets/81476/15151885/bba8c738-1698-11e6-8519-204c485c9e77.png)
## Julia

![julia](http://fonnesbeck-dropshare.s3.amazonaws.com/Screen-Shot-2016-05-10-10-26-28.png)

System information:

Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)]

Kernel: R version 3.2.5 (2016-04-14) via IRKernel 0.5

**Comment by willingc** [comment]
@Carreau @takluyver Thoughts? I'm seeing the same behavior as Chris (thanks for filing the issue) using the IJulia 0.4.5 kernel with similar OS config using Chrome or Firefox.

**Comment by takluyver** [comment]
I also see it, but I don't know what's causing it. There's no error in the JS console.

**Comment by Carreau** [comment]
It's the same that webpack that f**-up #1431 too, `require` just does not
work anymore, or at least not correctly, and there are basically 2
different CodeMirror library loaded on the page. So the mode is indeed
loaded correctly, but attached to the wrong copy of the module, so when the
cell highlighting changes, codemirror will just not find the mode, and give
up.

**Comment by Carreau** [comment]
And that unfortunately **is** #1047, that I just bisected, so the introduction of webpack **did** break all the kernels and many custom js and extensions.

Ping @ellisonbg , @fperez , @jdfreder as this is pretty important.

**Comment by ellisonbg** [comment]
Ouch, thanks for tracking this down. I am traveling more today. @jdfreder
is going to work on Friday for us and may be able to help us figure this
out...

On Tue, May 10, 2016 at 10:52 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> And that unfortunately *is* #1047
> <https://github.com/jupyter/notebook/pull/1047>, that I just bisected, so
> the introduction of webpack *did* break all the kernels and many custom
> js and extensions.
>
> Ping @ellisonbg <https://github.com/ellisonbg> , @fperez
> <https://github.com/fperez> , @jdfreder <https://github.com/jdfreder> as
> this is pretty important.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1439#issuecomment-218237295>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
FWIW. When I started the notebook the output to the terminal had a message: 
```
It looks like you're running the notebook from source.
    If you're working on the Javascript of the notebook, try running

        npm run build:watch

    in another terminal window to have the system incrementally
    watch and build the notebook's JavaScript for you, as you make changes.
```

Doing as instructed I opened another terminal window and ran this at the notebook source root directory and got these Babel errors:

<img width="928" alt="screen shot 2016-05-10 at 9 50 50 am" src="https://cloud.githubusercontent.com/assets/2680980/15155024/7edf403c-1695-11e6-855a-2807346ed2ed.png">

**Comment by Carreau** [comment]
These are not errors, they are notes. Perfectly fine.

The issue is that webpack create a main.min.js, and an index.js . index.js
is meant to map the require calls to bundled modules, but main and index
end up being 2 different namespace, each with their own module versions.

**Comment by willingc** [comment]
@Carreau Thanks for the explanation. Too many JS details :P I appreciate the detailed explanation of the current issue 👍

**Comment by MatthewSteen** [comment]
Using `%%script ruby` instead of the `%%ruby` shortcut enables syntax highlighting for Ruby ([jupyter/help/issues/43](https://github.com/jupyter/help/issues/43)).

**Comment by willingc** [comment]
Thanks @MatthewSteen for posting this in both locations.

**Comment by Carreau** [comment]
Reopening as #1490 seem to be only mitigating the issue without fixing the underlying behavior. And rely on the hack that `require` is also name `requirejs` in browser.

In particular the fix cannot be applied to the following codemirror modes:

```
django/django.js:        require("../../addon/mode/overlay"));
dockerfile/dockerfile.js:    mod(require("../../lib/codemirror"), require("../../addon/mode/simple"));
factor/factor.js:    mod(require("../../lib/codemirror"), require("../../addon/mode/simple"));
gfm/gfm.js:    mod(require("../../lib/codemirror"), require("../markdown/markdown"), require("../../addon/mode/overlay"));
handlebars/handlebars.js:    mod(require("../../lib/codemirror"), require("../../addon/mode/simple"), require("../../addon/mode/multiplex"));
htmlembedded/htmlembedded.js:        require("../../addon/mode/multiplex"));
modelica/modelica.js:    mod(require("../../lib/codemirror"));
nsis/nsis.js:    mod(require("../../lib/codemirror"), require("../../addon/mode/simple"));
rst/rst.js:    mod(require("../../lib/codemirror"), require("../python/python"), require("../stex/stex"), require("../../addon/mode/overlay"));
rust/rust.js:    mod(require("../../lib/codemirror"), require("../../addon/mode/simple"));
tornado/tornado.js:        require("../../addon/mode/overlay"));
twig/twig.js:    mod(require("../../lib/codemirror"),  require("../../addon/mode/multiplex"));
vue/vue.js:        require("../../addon/mode/overlay"),
```

Also the loading `addon`, `keymap`, and `theme` in codemirror is likely still broken.

**Comment by minrk** [comment]
This cannot be due to webpack on 4.x, because webpack is not used on 4.x. I was confused by a comment in #1511, so I thought this applied to 4.x. I checked, and this issue doesn't affect 4.x, where highlighting is already working just fine. I've update the milestone to 5.0, accordingly.

**Comment by Carreau** [comment]
Hum weird. I was pretty sure I tried.

**Comment by takluyver** [comment]
I think this is fixed now that we've dropped webpack again.

**Comment by MatthewSteen** [comment]
I'm still seeing this on in Jupyter for 2.7. 

---

**Jupyter - long cell magic applies Python highlighting to Ruby**

![image](https://cloud.githubusercontent.com/assets/8397034/22472054/af82af12-e791-11e6-9ad0-c8a4a9fe2caa.png)
 
**Jupyter - short cell magic highlights all code as a string**

![image](https://cloud.githubusercontent.com/assets/8397034/22472235/453a7526-e792-11e6-9ea0-bf576128f295.png)

---

**Atom**

![image](https://cloud.githubusercontent.com/assets/8397034/22472169/0e137188-e792-11e6-9484-8eba86f6b140.png)

**Comment by takluyver** [comment]
@MatthewSteen I don't think either of those is the same issue; this was about other kernels, rather than cell magics.

I think the case with `%%script` is expected: we don't try to do anything clever with highlighting for the `%%script` cell magic, so it will get the default syntax highlighting.

The issue with %%ruby is not expected, though - please can you file a new issue for that?
