### ISSUE TITLE
Wrong focus when remove many cells

### ISSUE THREAD

**Issue by rgaiacs** [jupyter/notebook#2050]
# Steps to reproduce

1. Open a notebook.
2. Select many cells (start with the first one). The sum of height of the selected cells must be greater than the height of the visible area.
3. Delete the cells.

# Expected behaviour

The focus is on the next cell of the last removed cell and that cell is on the visible area.

# Current behaviour

The focus is on the next cell of the last removed cell **but that cell is not on the visible area.**

# Environment

- Notebook server: 4.2.1-1b1e6f608d
- Web browser: Chromium Version 55.0.2883.87 (64-bit) **and** Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

# Extra

[Video showing the bug.](https://github.com/jupyter/notebook/files/716521/video.zip)

**Comment by gnestor** [comment]
This is a bug. I will take a look at this when I have a chance, but the culprit is here: https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/notebook.js#L1100-L1167

**Comment by takluyver** [comment]
@gnestor I'm planning to aim for a 5.0 release quite soon. Do you think you'll have time to get to this?

**Comment by gnestor** [comment]
Ya, I'll work on this today 👍

**Comment by takluyver** [comment]
@gnestor did you get a chance to look at this?

**Comment by gnestor** [comment]
I actually can't reproduce this anymore. I do notice that undoing a delete cells will add the cells back out of order which is a separate bug. @rgaiacs Can you provide an example notebook to help reproduce?

**Comment by rgaiacs** [comment]
@gnestor Can you try 
[bug-353-example.zip](https://github.com/jupyter/notebook/files/754506/bug-353-example.zip).

**Comment by takluyver** [comment]
@gnestor have you had a chance to look at @rgaiacs' example?

**Comment by gnestor** [comment]
It may have been fixed in master because I still can't reproduce, even with this example notebook. See the following screen cap and follow along with me:

1. Select cells from "Episode 2" up until "Episode 3"
2. Scroll to top and "Delete cells"
3. As expected, "Episode 3" cells and below are moved to visible range at the top of the notebook

![screencap](http://g.recordit.co/cz2VKqOYEC.gif)

**Comment by gnestor** [comment]
@rgaiacs If you're so inclined, try cloning the master branch of this repo and [installing locally](https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst#installing-the-jupyter-notebook). If you can still reproduce on master, please let me know how.

**Comment by rgaiacs** [comment]
@gnestor Testing with 3e1f54502d200e25647dce85f8a441e2a4d08b42.

I can reproduce the behaviour that you describe.

> 1. Select cells from "Episode 2" up until "Episode 3"
> 2. Scroll to top and "Delete cells"
> 3. As expected, "Episode 3" cells and below are moved to visible range at the top of the notebook

The behaviour that I want is

> 1. Select cells from "Episode 2" up until "Episode 3"
> 2. "Delete cells"
> 3. "Episode 3" cells and below are moved to the top of the notebook and scroll bar is change to the top.

The 3rd step should be more general, i.e. if I delete cells from "Episode 3" up until "Episode 4" I should have "Episode 4" visible on my screen.

**Comment by takluyver** [comment]
I can reproduce what @rgaiacs describes. The key difference is: don't scroll to the top before deleting cells. When I press `d, d`, the 'Episode 3' cell, now the first in the notebook, is above the visible area on my screen. I agree that ideally the selected cell should be visible after deleting cells.

Pinging @ellisonbg for a focus related issue, as he worked on this stuff quite a bit before.

**Comment by gnestor** [comment]
> 3. "Episode 3" cells and below are moved to the top of the notebook and scroll bar is change to the top.

This is what I'm seeing in master:

![screencap](http://g.recordit.co/yfqwuO596l.gif)

@rgaiacs @takluyver So that we're on the same page: What is unexpected about the above screen capture?

Additionally, when I delete cells from "Episode 3" to "Episode 4", the scroll position isn't changed which is what I expect:

![screencap2](http://g.recordit.co/MWY4B8kBPe.gif)

**Comment by rgaiacs** [comment]
@gnestor I believe that this bug was fixed already. I tested again from scratch

~~~
$ git remote -v
origin	git@github.com:jupyter/notebook.git (fetch)
origin	git@github.com:jupyter/notebook.git (push)
$ git fetch origin
$ git rev-parse origin/master
a33d136cb03827edbad4a538979b3cced86057d2
$ git rev-parse HEAD
a33d136cb03827edbad4a538979b3cced86057d2
$ python -m pip install -e . --user
Obtaining file:///home/raniere/src/notebook
Requirement already satisfied: jinja2 in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: tornado>=4 in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: ipython_genutils in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: traitlets>=4.2.1 in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: jupyter_core in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: jupyter_client in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: nbformat in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: nbconvert in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: ipykernel in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: terminado>=0.3.3 in /home/raniere/.local/lib/python3.5/site-packages (from notebook==5.0.0.dev0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/raniere/.local/lib/python3.5/site-packages (from jinja2->notebook==5.0.0.dev0)
Requirement already satisfied: decorator in /home/raniere/.local/lib/python3.5/site-packages (from traitlets>=4.2.1->notebook==5.0.0.dev0)
Requirement already satisfied: six in /home/raniere/.local/lib/python3.5/site-packages (from traitlets>=4.2.1->notebook==5.0.0.dev0)
Requirement already satisfied: pyzmq>=13 in /home/raniere/.local/lib/python3.5/site-packages (from jupyter_client->notebook==5.0.0.dev0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/raniere/.local/lib/python3.5/site-packages (from nbformat->notebook==5.0.0.dev0)
Requirement already satisfied: testpath in /home/raniere/.local/lib/python3.5/site-packages (from nbconvert->notebook==5.0.0.dev0)
Requirement already satisfied: mistune!=0.6 in /home/raniere/.local/lib/python3.5/site-packages (from nbconvert->notebook==5.0.0.dev0)
Requirement already satisfied: pygments in /home/raniere/.local/lib/python3.5/site-packages (from nbconvert->notebook==5.0.0.dev0)
Requirement already satisfied: bleach in /home/raniere/.local/lib/python3.5/site-packages (from nbconvert->notebook==5.0.0.dev0)
Requirement already satisfied: entrypoints>=0.2.2 in /home/raniere/.local/lib/python3.5/site-packages (from nbconvert->notebook==5.0.0.dev0)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/raniere/.local/lib/python3.5/site-packages (from nbconvert->notebook==5.0.0.dev0)
Requirement already satisfied: ipython>=4.0.0 in /home/raniere/.local/lib/python3.5/site-packages (from ipykernel->notebook==5.0.0.dev0)
Requirement already satisfied: ptyprocess in /home/raniere/.local/lib/python3.5/site-packages (from terminado>=0.3.3->notebook==5.0.0.dev0)
Requirement already satisfied: html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 in /home/raniere/.local/lib/python3.5/site-packages (from bleach->nbconvert->notebook==5.0.0.dev0)
Requirement already satisfied: setuptools>=18.5 in /home/raniere/anaconda3/envs/jupyter/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from ipython>=4.0.0->ipykernel->notebook==5.0.0.dev0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /home/raniere/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->notebook==5.0.0.dev0)
Requirement already satisfied: pickleshare in /home/raniere/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->notebook==5.0.0.dev0)
Requirement already satisfied: simplegeneric>0.8 in /home/raniere/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->notebook==5.0.0.dev0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /home/raniere/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->notebook==5.0.0.dev0)
Requirement already satisfied: wcwidth in /home/raniere/.local/lib/python3.5/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel->notebook==5.0.0.dev0)
Installing collected packages: notebook
  Found existing installation: notebook 5.0.0.dev0
    Uninstalling notebook-5.0.0.dev0:
      Successfully uninstalled notebook-5.0.0.dev0
  Running setup.py develop for notebook
Successfully installed notebook
$ jupyter --version                
4.3.0
~~~

and looks OK. I think that I was using a old version and didn't update properly last time. Thanks for your help.

**Comment by takluyver** [comment]
Sorry, but I can still reproduce this on master. When I follow the same steps as the first of @gnestor's two screencasts in his last post, my view does not scroll to the top cell 'Episode 3'. I'm not sure what the difference is, but I can reproduce this every time I try, in both Firefox and Chromium.

I updated to master just now and rebuilt the js.

**Comment by takluyver** [comment]
Also tried disabling extensions, still see it.

**Comment by jtpio** [comment]
Closing as the classic notebook UI has now been moved to https://github.com/jupyter/nbclassic.

Feel free to open a new issue there if it is still relevant, thanks!
