### ISSUE TITLE
Too much printing to stdout crashes Jupyter Notebook

### ISSUE THREAD

**Issue by crawles** [jupyter/notebook#2364]
If the output is too large, due to, for example, user error with an infinitely repeating output, Jupyter Notebook freezes without allowing the user to kill the kernel (becomes unresponsive). Whereas in a terminal, a cntrl-c is able to stop the execution in its tracks. 

For a test case see below. It would be nice if such a command, while silly it is, didn't freeze Jupyter.

```
while 1:
    print 1
```

**Comment by jasongrout** [comment]
When I run the above code in Notebook 5 RC2, the interface is responsive and I can hit the 'interrupt kernel' button to stop the computation. I'm a bit surprised the iopub limits didn't kick in for this, @minrk.

Can you try in Jupyter Notebook 5 (just released)?

**Comment by crawles** [comment]
@jasongrout Thank you. Just downloaded Jupyter 5 and the problem is resolved on my end. I can hit "interrupt kernel" successfully. If I try something more taxing, it still works - you can hit interrupt ( while 1: print [1]*1000 ). Though, it does experience significant slowdown/laggyness until the cell output is minimized. Might be nice if it default options limited output by default...

**Comment by gnestor** [comment]
It looks like this is resolved. @crawles Feel free to open a new issue regarding:

> Might be nice if it default options limited output by default...

**Comment by mikkokotila** [comment]
I seem to be suffering from this problem still, my version is: 

jupyter==1.1.0
jupyter-client==5.2.1
jupyter-console==5.2.0
jupyter-core==4.4.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.2

Any idea of what I can do about this? It would be wonderful to rid once and for all the burden of freezing browser in these similar cases ;)

**Comment by gnestor** [comment]
@mikkokotila Agreed! Can you please provide step-by-step instructions to reproduce this issue? If running more than a cell or two, please provide an example notebook 👍

**Comment by mijumoto** [comment]
I ran my notebook with a grid search (verbose = 2), 800k estimators. The notebook crashed and is not letting me in as the OP describes. Lost 7 hours of train time right there because it didn't finish the job. I had to edit the HTML code and remove all the verbose output to be able to get back in.

**Comment by gnestor** [comment]
@mijumoto This is an unfortunate limitation of current browsers and the DOM: runaway processes in the browser will eventually freeze/crash it. I agree that we should prevent this from happening in the notebook somewhere but I can't think of an obvious way to detect when a process is _runaway_. We certainly welcome contributions to improve this situation...
