### ISSUE TITLE
ImportError: No module named paths while running the jupyter notebook

### ISSUE THREAD

**Issue by ankeshanand** [jupyter/notebook#270]
I upgraded jupyter via `pip install --upgrade jupyter`, but I when I try to launch a new notebook using `jupyter notebook`, I am getting an error: **ImportError: No module named paths**.

Here's the full traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 3, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 83, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths
```

**Comment by minrk** [comment]
What do you get from `pip list` and `python -m IPython --version`?

**Comment by ankeshanand** [comment]
`pip list` gives me `ipython (4.0.0)`, 
`python -m IPython --version` gives me `1.2.1`.

**Comment by minrk** [comment]
Okay, and what do you get from `cat /usr/local/lib/python2.7/dist-packages/*.pth`?

**Comment by ankeshanand** [comment]
It's a long output, I have at pastebin here: http://pastebin.com/yZqYqw0y

**Comment by minrk** [comment]
Yup, it's exactly as I suspected - `/usr/lib/python2.7/dist-packages` should not be in `/usr/local/lib/python2.7/dist-packages/*.pth`. If you remove that, In fact, probably none of the

I see lots of eggs in there, which suggest that you have used easy_install. If you have time, I would recommend removing anything you've installed with easy_install, removing all your .pth files, and installing again with only pip. easy_install is a bit of a nightmare, and all the lines of code that start with `import` in there are a source of frequent and major problems.

**Comment by ankeshanand** [comment]
Thanks @minrk, works perfect now!

**Comment by whophil** [comment]
I have this same issue, but my `/usr/lib/python2.7/dist-packages/` directory is empty.

```
phil@phil-cube:~$ jupyter notebook
Traceback (most recent call last):
  File "/home/phil/Enthought/Canopy_64bit/User/bin/jupyter-notebook", line 8, in <module>
    from notebook.notebookapp import main
  File "/home/phil/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/notebookapp.py", line 83, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths

phil@phil-cube:~$ pip list | grep ipython
ipython (4.0.0)
ipython-genutils (0.1.0)
ipython4 (4.0.0)

phil@phil-cube:~$ python -m IPython --version
1.2.1
```

**Comment by minrk** [comment]
@whophil the issue is the same. There is probably a file called `easy-install.pth` on your system, which inappropriate information in it. You can fix this by removing the offending line from `easy-install.pth`. It may not be `/usr/lib/`, it may be `/usr/local/lib`. There should be *no* directories called `dist-packages` or `site-packages` listed in any `.pth` file. If there is, it was caused by a bug in setuptools, and should be removed.

**Comment by renuad** [comment]
Hello,

I am also using the Canopy distribution and have the same issue with jupyter notebook: 
Traceback (most recent call last):
  File "/Users/renaudperson/Library/Enthought/Canopy_64bit/User/bin/jupyter-notebook", line 8, in <module>
    from notebook.notebookapp import main
  File "/Users/renaudperson/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/notebookapp.py", line 83, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths

with
ipython (4.0.0)
python -m IPython --version
1.2.1

there is no *.pth in the directory
/Users/renaudperson/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/

and there is no dist or site-packages directory in /usr/local/lib/

regards

**Comment by whophil** [comment]
I fixed my problem by uninstalling/reinstalling IPython via the Canopy package manager. I then moved my `ipython_notebook_config.py` to the `.jupyter/jupyter_notebook_config.py`. Perhaps there is a sleeker solution, but I didn't have time to find it.

**Comment by renuad** [comment]
Thx whophil, It works like a charm by just uninstalling/reinstalling IPython via the Canopy package manager!!!!

**Comment by codeAshu** [comment]
when I run the comman ``ipython  notebook --no-browser --ip=* --port=8889`` . I also face the same issue. I was facing this problem tried everything, then installed conda package, but still the problem is there.

``
Traceback (most recent call last):
  File "/root/yes/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 48, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
  File "/usr/local/lib/python2.7/dist-packages/pickleshare.py", line 41, in <module>
    from path import path as Path
ImportError: No module named path
``

**Comment by jeremy-rutman** [comment]
upvote for minrk's solution of 6 Oct. which worked for me as well

"Yup, it's exactly as I suspected - /usr/lib/python2.7/dist-packages should not be in /usr/local/lib/python2.7/dist-packages/*.pt"

**Comment by srikarrohit** [comment]
Yeah. Just moving easy-install.pth out of /usr/local/lib/python2.7/dist-packages/ helped.

**Comment by olologin** [comment]
I've just solved this problem, i updated my ipython with pip3 install -U ipython, but i think this problem was solved because pip3 installed path.py as dependency while updating.

**Comment by imAJine** [comment]
I am still getting the same issue. 
ImportError: No module named paths

Can you guys please provide some solution for it.

**Comment by takluyver** [comment]
That error means it's finding an older version of IPython when it tries to import it. Uninstall and reinstall IPython, and make sure that it's finding the copy you think it should be using.

**Comment by wilsonmichael** [comment]
`pip install path.py` fixed this issue for me. Found the solution [in this issue](https://github.com/jupyter/notebook/issues/525)

**Comment by monkeyxite** [comment]
Still the issue occurs after uninstalled ipython/jupyter, and removed easy_install.pth.

Need more information to resolve the issue?

**Comment by minrk** [comment]
That means there's still an old IPython being imported. Try to verify with `python -c 'import IPython; print(IPython.__file__)'`

**Comment by Himscipy** [comment]
Hi,
I am facing the same error and even removing the easy_install.pth didn't helped.

I tried your instruction.
python -c 'import IPython; print(IPython.__file__)'

Output was following.

/usr/local/lib/python2.7/dist-packages/IPython/__init__.pyc

what is to be inferred from this..?? 

I even tried pip install path.py but still the error persist.

Thanks.

**Comment by monkeyxite** [comment]
Still no clue ...

```shell
$python -c 'import IPython; print(IPython.file)'                                                                                                                        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'file'

$python -c 'import IPython; print(dir(IPython))'                                                                                                                        
['Application', 'Config', 'InteractiveShell', 'TryNext', '__author__', '__builtins__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__version__', 'absolute_import', 'config', 'core', 'embed', 'embed_kernel', 'extensions', 'external', 'extract_module_locals', 'get_ipython', 'lib', 'os', 'release', 'start_ipython', 'start_kernel', 'sys', 'sys_info', 'terminal', 'test', 'testing', 'utils', 'version_info']

$ipython --version 
1.2.1

$ python -c 'import sys; print(sys.path)'                                                                                                                                
['', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2']

$ls /usr/lib/python2.7/dist-packages|grep IPython                                                                                                                     
IPython

$ls /usr/lib/python2.7/dist-packages|grep pth                                                                                                                           
gtk-2.0-pysupport-compat.pth
PILcompat.pth
pygtk.pth
python-support.pth
repoze.lru-0.6-nspkg.pth
setuptools.pth
ubuntu-sso-client.pth
wx.pth
zope.interface-4.0.5-nspkg.pth

```

**Comment by minrk** [comment]
> what is to be inferred from this..??

This means that the IPython being imported is the very-old one installed by `apt-get`. If you have done `pip install --upgrade ipython`, that should install a newer IPython in `/usr/local/lib/python2.7/dist-packages`. `/usr/lib/python2.7/dist-packages` being on the front of sys.path means that there is an `easy-install.pth` file with this path, which should be removed. It is caused by a bug in setuptools. The most likely location for this file is:

    /usr/local/lib/python2.7/dist-packages/easy-install.pth

You can check for this setuptools bug with:

    grep dist-packages /usr/local/lib/python2.7/dist-packages/*.pth

If the file is where I expect it is, the fix should be to remove the file:

    /usr/local/lib/python2.7/dist-packages/easy-install.pth

While you are at it, make sure your pip/setuptools are up to date:

    pip install --upgrade setuptools pip

**Comment by monkeyxite** [comment]
@minrk 
Problem solved by 'apt-get remove ipython'. 

Cheers!

**Comment by rkotwani** [comment]
@minrk after upgrading the setup tools and pip, "import path" worked in python and in ipython.

**Comment by nkarapetyan** [comment]
Hi all,
I have same issue and I have already tried everything above mentioned.
There is no easy-install.pth file in any of mentioned directories.
As for versions, both pip list an python -m IPython --version give me the same result 4.1.1.

Please give some ideas how to solve this. Many thanks.

**Comment by takluyver** [comment]
Have you tried `apt-get remove ipython` - or the equivalent for your platform?

That error message means that it is finding an older version of IPython for whatever reason. So try removing every copy of IPython you can track down, and then installing it again.

**Comment by nkarapetyan** [comment]
Yes, I did already, but nothing is changed.

**Comment by takluyver** [comment]
There is probably another copy of IPython hiding somewhere on your system. What platform are you on, and what might you have used to install IPython (e.g. apt, conda, pip)

**Comment by nkarapetyan** [comment]
Solved: My system was crashed yesterday, after installing and uninstalling
couple of things. But, now after formatting ipython seams working. In any
case the problem was with the versions, as You said. Thank You so much for
help!

**Comment by arnavsharma93** [comment]
Hello

I was facing the same problem on my mac. As suggested by @minrk, removing `easy-install.pth` from `/Library/Python/2.7/site-packages` did the trick.

**Comment by siyi8088** [comment]
@minrk  thank you!

**Comment by psahu** [comment]
I got the same import error while opening ipython notebook after I upgraded my pip. I tried everything suggested above including uninstalling anaconda (which did not uninstall for some reason) but nothing worked. While reviewing anaconda documentation, I thought of updating my conda and anaconda to see if that would help. Luckily, it did the trick. Once again, my jupyter notebook is up and running. 
Lesson learned: When you upgrade pip, make sure to update your conda and anaconda as well. 
The commands I used to resolve the issue are:
pip install --upgrade pip
conda update conda
conda update anaconda

**Comment by sarveshj** [comment]
I was facing the same issue. It got resolved by doing the following: 
`pip3 install --upgrade pip`
`pip3 install jupyter`

**Comment by dlewin** [comment]
whereas the jupyter main page also recommends pip3 install --upgrade pip etc
 , the  pip3 install -U ipython from olologin was the solution for me

**Comment by sarveshj** [comment]
I was able to solve the issue by install pip as follows, without reinstalling jupyter

``sudo apt-get install python3-setuptools``
``sudo easy_install3 pip``

**Comment by NonMundaneDev** [comment]
> I've just solved this problem, i updated my ipython with pip3 install -U ipython, but i think this problem was solved because pip3 installed path.py as additional dependency while updating.

Worked like a charm. Thanks!

**Comment by aakinomm** [comment]
I am unable to execute the code 
data_to_use.drop(axis=1, columns=['Inbound']) # X is a dataframe
X = X.drop(axis=1, columns=['Label'])

y1 = data_to_use['Inbound'].values # y is an array
y2 = data_to_use['Label'].value

I am getting the below error.Pls help me to correct it.Even I removed the easy_install. pth
     Thanks in Advance 
KeyError                                  Traceback (most recent call last)
<ipython-input-8-d4478718038f> in <module>
----> 1 X = data_to_use.drop(axis=1, columns=['Inbound']) # X is a dataframe
      2 X = X.drop(axis=1, columns=['Label'])
      3 
      4 y1 = data_to_use['Inbound'].values # y is an array
      5 y2 = data_to_use['Label'].values

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   3995             level=level,
   3996             inplace=inplace,
-> 3997             errors=errors,
   3998         )
   3999 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   3934         for axis, labels in axes.items():
   3935             if labels is not None:
-> 3936                 obj = obj._drop_axis(labels, axis, level=level, errors=errors)
   3937 
   3938         if inplace:

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py in _drop_axis(self, labels, axis, level, errors)
   3968                 new_axis = axis.drop(labels, level=level, errors=errors)
   3969             else:
-> 3970                 new_axis = axis.drop(labels, errors=errors)
   3971             result = self.reindex(**{axis_name: new_axis})
   3972 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in drop(self, labels, errors)
   5016         if mask.any():
   5017             if errors != "ignore":
-> 5018                 raise KeyError(f"{labels[mask]} not found in axis")
   5019             indexer = indexer[~mask]
   5020         return self.delete(indexer)

KeyError: "['Inbound'] not found in axis"
