### ISSUE TITLE
object name + dot + tab does return list of methods twice in jupyter notebook

### ISSUE THREAD

**Issue by ilyagrigoryev** [jupyter/notebook#3238]
I've installed jupyter notebook through `pip install`, py3. Local running within cmd.

![screenshot](https://i.stack.imgur.com/ng6v2.png)

**Comment by takluyver** [comment]
The bug is actually coming from IPython. It should be fixed when we release 6.3.

https://github.com/ipython/ipython/pull/10969

**Comment by Phil807** [comment]
Hi,
Has this issue been fixed?
I still have that bug in my jupyter notebook.
