### ISSUE TITLE
Jupyter Notebook throws 'IOLoop' AttributeError with tornado=5.0

### ISSUE THREAD

**Issue by chenchen2015** [jupyter/notebook#3407]
### Observation
After updating to `tornado=5.0` using `conda update --all -y`, jupyter notebook cannot start and was throwing errors:
```
$ jupyter notebook& 
[1] 3527                                
Traceback (most recent call last):                                                                  
  File "/home/chenchen2015/anaconda3/bin/jupyter-notebook", line 7, in <module>  
    from notebook.notebookapp import main                                        
  File "/home/chenchen2015/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>                                                    
    ioloop.install()                    
  File "/home/chenchen2015/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install                                                    
    assert (not ioloop.IOLoop.initialized()) or \                                
AttributeError: type object 'IOLoop' has no attribute 'initialized'              
```
This was seen on Ubuntu 17.10 with Anaconda 5.1.0 x64.

### Solution
Similar to #3397, this is solved by manually downgrading back to `tornado=4.5.3` with `conda install tornado=4.5.3`, hence it seems to be a breaking change caused by tornado 5.0 releases

**Comment by fterbo** [comment]
To be clear, this was not anaconda, and it was getting everything on a fresh install from pip.  We do not install pyzmq or tornado directly (although installing tornado directly did fix it).

**Comment by edurand** [comment]
Hello,
I'm having ta similar issue with pyzmq == 17.0.0 and tornado == 5.0.1. To be clear, jupyter is indeed able to start with pyzmq updated. However, as soon as starting a new notebook or restarting an old one, I get: 
AttributeError: type object 'ZMQIOLoop' has no attribute 'initialized'
Thanks

**Comment by takluyver** [comment]
That probably means that your kernel is running in an environment where you still have an older version of pyzmq, while your notebook is running somewhere with a newer pyzmq.

**Comment by edurand** [comment]
Thanks - how would I diagnose this?

**Comment by takluyver** [comment]
Use `jupyter kernelspec list` to see where your kernelspecs are. That shows you some folders - inside each one should be a `kernel.json` file pointing to which executable that kernelspec will use.

If there's an entry which ends with `ipykernel/resources`, then it won't have a `kernel.json`, and that kernel type will be launched with the same Python that the notebook server runs on.

**Comment by edurand** [comment]
This is strange, the kernels all point to the right place. All works fine
in a fresh environment, too.

**Comment by wesg52** [comment]
I have been having the same issue. I upgraded pyzmq to 17.0.0 globally and the issue has not been solved.

**Comment by takluyver** [comment]
If you're getting the same traceback as in the original post, then it must be using an older version of pyzmq somewhere. Check for different virtualenvs/conda envs/Python versions.

**Comment by krish1999** [comment]
thanks, it solved my problem

**Comment by ajgpitch** [comment]
I followed all the update tornado and pyzmq suggestions, still same error in old conda env. I made a fresh conda env - no error. I made the comparison.
```
conda install jupyter
```
fixed my old conda env

**Comment by rohannaidu** [comment]
Upgrading pyzmq didn't work for me, but as a few other recent comments here have mentioned, downgrading tornado did it!

**Comment by jsutch** [comment]
Still a problem on OSX 10.13.6 (17G5019) with pip installed latest versions of everything and only the intended versions/environments for pyzmq/tornado/et al. Downgrading tornado to 4.5.3 still works.

**Comment by rafiulgits** [comment]
> Hello,
> I'm having ta similar issue with pyzmq == 17.0.0 and tornado == 5.0.1. To be clear, jupyter is indeed able to start with pyzmq updated. However, as soon as starting a new notebook or restarting an old one, I get:
> AttributeError: type object 'ZMQIOLoop' has no attribute 'initialized'
> 
> Downgrading tornado to 4.5.3 solves the issue.
> Thanks
