### ISSUE TITLE
Jupyter notebook fails to run (older iMac with OSx 10.8 - ImportError/Symbol not found)

### ISSUE THREAD

**Issue by microbially** [jupyter/notebook#4214]
I'm working on getting some scripts running on various machines. These scripts are built to run in jupyter notebook, and I've gotten everything working fine on my coworker's laptop (OSx 10.13) and my laptop (Windows 8.1). However, we really want to get them running on a communal iMac, which is currently running OSx 10.8. 

After installing Miniconda 2 on the machine, creating an environment, and using `conda install jupyter` with apparent success, `jupyter notebook` gave me this error:

> Traceback (most recent call last):
>   File "/Users/elisa/miniconda2/envs/barti_env/bin/jupyter-notebook", line 7, in <module>
>     from notebook.notebookapp import main
>   File "/Users/elisa/miniconda2/envs/barti_env/lib/python2.7/site-packages/notebook/notebookapp.py", line 46, in <module>
>     from zmq.eventloop import ioloop
>   File "/Users/elisa/miniconda2/envs/barti_env/lib/python2.7/site-packages/zmq/__init__.py", line 47, in <module>
>     from zmq import backend
>   File "/Users/elisa/miniconda2/envs/barti_env/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
>     reraise(*exc_info)
>   File "/Users/elisa/miniconda2/envs/barti_env/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
>     _ns = select_backend(first)
>   File "/Users/elisa/miniconda2/envs/barti_env/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
>     mod = __import__(name, fromlist=public_api)
>   File "/Users/elisa/miniconda2/envs/barti_env/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
>     from . import (constants, error, message, context,
> ImportError: dlopen(/Users/elisa/miniconda2/envs/barti_env/lib/python2.7/site-packages/zmq/backend/cython/error.so, 2): Symbol not found: _memset_s
>   Referenced from: /Users/elisa/miniconda2/envs/barti_env/lib/libsodium.23.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /Users/elisa/miniconda2/envs/barti_env/lib/libsodium.23.dylib

I've found similar issues online [here](https://stackoverflow.com/questions/51049779/neither-anaconda-navigator-or-jupyter-notebook-will-open) (same OS, identical issue, but no solution aside from those in [this](https://github.com/ContinuumIO/anaconda-issues/issues/520) thread, which did not work for me) and [here](https://github.com/jupyter/notebook/issues/1632) (similar issue, no OS given). Based on the solutions offered in the second thread, I uninstalled and reinstalled basically everything (removed miniconda and python completely from the machine and started over, did remove/install for any package that seemed remotely related - zeromq, pyzmq, libsodium), and tried using different versions of python 2.7. Nothing has worked--I get the same error no matter what I do here. 

Is this a compatibility issue with the OS, and is it fixable? We are looking into upgrading the OS, but we might need administrative permission and I would love to come up with a solution.

**Comment by minrk** [comment]
Can you show `conda list` and `pip list`?

This means that pyzmq is linked against a different version of libsodium than is installed. This *should* be fixed in the latest version of the package on conda-forge. If you are not using conda-forge, it may be an issue with the pyzmq package from anaconda.

Try updating pyzmq and libsodium and see if you get a working combination:

    conda install pyzmq libsodium

**Comment by microbially** [comment]
Thank you for the suggestions! I just used `conda install -c conda-forge` for pyzmq, libsodium, and zeromq. Still encountering the same error.

Here are the current lists:

`conda list`

```
# Name                    Version                   Build  Channel
appnope                   0.1.0            py27hb466136_0  
backports                 1.0                      py27_1  
backports.shutil_get_terminal_size 1.0.0                    py27_2  
backports_abc             0.5              py27h6972548_0  
blas                      1.0                         mkl  
bleach                    3.0.2                    py27_0  
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py27_1000    conda-forge
configparser              3.5.0            py27hc7edf1b_0  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py27_0  
entrypoints               0.2.3                    py27_2  
enum34                    1.1.6                    py27_1  
expat                     2.2.6                h0a44026_0  
functools32               3.2.3.2                  py27_1  
futures                   3.2.0                    py27_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.0                      118  
ipaddress                 1.0.22                   py27_0  
ipykernel                 4.10.0                   py27_0  
ipython                   5.8.0                    py27_0  
ipython_genutils          0.2.0            py27h8b9a179_0  
ipywidgets                7.4.2                    py27_0  
jinja2                    2.10                     py27_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py27hd9b497e_0  
jupyter                   1.0.0                    py27_7  
jupyter_client            5.2.3                    py27_0  
jupyter_console           5.2.0                    py27_1  
jupyter_core              4.4.0                    py27_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.35               ha441bb4_0  
libsodium                 1.0.16               h470a237_1    conda-forge
markupsafe                1.0              py27h1de35cc_1  
mistune                   0.8.4            py27h1de35cc_0  
mkl                       2019.0                      118  
nbconvert                 5.3.1                    py27_0  
nbformat                  4.4.0            py27hddc86d0_0  
ncurses                   6.1                  h0a44026_0  
notebook                  5.7.0                    py27_0  
numpy                     1.11.3          py27h6a91979_10  
numpy-base                1.11.3          py27h8a80b8c_10  
openssl                   1.0.2p               h470a237_1    conda-forge
pandas                    0.18.1              np111py27_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py27_1  
pathlib2                  2.3.2                    py27_0  
pcre                      8.42                 h378b8a2_0  
pexpect                   4.6.0                    py27_0  
pickleshare               0.7.5                    py27_0  
pip                       18.1                     py27_0  
prometheus_client         0.4.2                    py27_0  
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
ptyprocess                0.6.0                    py27_0  
pygments                  2.2.0            py27h1a556bb_0  
pyqt                      5.9.2            py27h655552a_2  
python                    2.7.15               h43f7c74_0    conda-forge
python-dateutil           2.7.5                    py27_0  
pytz                      2018.7                   py27_0  
pyzmq                     17.1.2           py27hae99301_1    conda-forge
qt                        5.9.6                h45cd832_2  
qtconsole                 4.4.2                    py27_0  
readline                  7.0                  h1de35cc_5  
scandir                   1.9.0            py27h1de35cc_0  
send2trash                1.5.0                    py27_0  
setuptools                40.5.0                   py27_0  
simplegeneric             0.8.1                    py27_2  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.19.8           py27h0a44026_0  
six                       1.11.0                   py27_1  
sqlite                    3.25.2               ha441bb4_0  
terminado                 0.8.1                    py27_1  
testpath                  0.4.2                    py27_0  
tk                        8.6.8                ha441bb4_0  
tornado                   5.1.1            py27h1de35cc_0  
traitlets                 4.3.2            py27hcf08151_0  
wcwidth                   0.1.7            py27h817c265_0  
webencodings              0.5.1                    py27_1  
wheel                     0.32.2                   py27_0  
widgetsnbextension        3.4.2                    py27_0  
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               hf3cbc9b_2  
```

`pip list`

```
Package                            Version    
---------------------------------- -----------
appnope                            0.1.0      
backports-abc                      0.5        
backports.shutil-get-terminal-size 1.0.0      
bleach                             3.0.2      
certifi                            2018.10.15 
configparser                       3.5.0      
decorator                          4.3.0      
entrypoints                        0.2.3      
enum34                             1.1.6      
functools32                        3.2.3.post2
futures                            3.2.0      
ipaddress                          1.0.22     
ipykernel                          4.10.0     
ipython                            5.8.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.4.2      
Jinja2                             2.10       
jsonschema                         2.6.0      
jupyter                            1.0.0      
jupyter-client                     5.2.3      
jupyter-console                    5.2.0      
jupyter-core                       4.4.0      
MarkupSafe                         1.0        
mistune                            0.8.4      
nbconvert                          5.3.1      
nbformat                           4.4.0      
notebook                           5.7.0      
numpy                              1.11.3     
pandas                             0.18.1     
pandocfilters                      1.4.2      
pathlib2                           2.3.2      
pexpect                            4.6.0      
pickleshare                        0.7.5      
pip                                18.1       
prometheus-client                  0.4.2      
prompt-toolkit                     1.0.15     
ptyprocess                         0.6.0      
Pygments                           2.2.0      
python-dateutil                    2.7.5      
pytz                               2018.7     
pyzmq                              17.1.2     
qtconsole                          4.4.2      
scandir                            1.9.0      
Send2Trash                         1.5.0      
setuptools                         40.5.0     
simplegeneric                      0.8.1      
singledispatch                     3.4.0.3    
six                                1.11.0     
terminado                          0.8.1      
testpath                           0.4.2      
tornado                            5.1.1      
traitlets                          4.3.2      
wcwidth                            0.1.7      
webencodings                       0.5.1      
wheel                              0.32.2     
widgetsnbextension                 3.4.2
```

**Comment by microbially** [comment]
Update: After upgrading to the latest OS, and making literally no changes to the environment, the issue was resolved. Seems to be entirely OS-specific.
