### ISSUE TITLE
500 Internal Server Error with latest Tornado

### ISSUE THREAD

**Issue by scribby182** [jupyter/notebook#4474]
Built a new conda environment today and found Jupyter Notebooks unable to load notebooks.  Clicking a notebook yielded a 500 Internal server error.  I believe the relevant error in the console was: " AttributeError: module 'tornado.web' has no attribute 'asynchronous'"

Seemed to coincide with either recent notebook version release or tornado version release. Fixed temporarily by:
```
    pip uninstall tornado
    pip install tornado=5.1.1
```

**Comment by david-waterworth** [comment]
I think this has been fixed, tornado 6.x had a compatibility issue with notebooks

https://github.com/jupyter/notebook/issues/4311#issuecomment-470151566

**Comment by scribby182** [comment]
Good call.  Updating nbconvert fixed things.

Strangely I had to do it twice.  First time said it updated, but then still showed 5.3.1 in pip list.  Second time actually stuck.
