### ISSUE TITLE
Jupyter notebook blank page on start up

### ISSUE THREAD

**Issue by kennanlau** [jupyter/notebook#4503]
Hello All Jupyters mates,

When I launch jupyter, I get a blank page with url: http://localhost:8888/tree

No Dashboard, to listing of current directory.
Just a blank page.
I removed all application & packages below and re-installed again and same blank page.
Tensorflow and python works inside of Windows Terminal, I can perform all functions in terminal but nothing would appear in the web broswer, Chrome, Edge, Firefox.

Any help would be greatly appreciated.

Thanks

**Windows 10
I installed the following in order:**

1. Miniconda 
2. conda create --name tensorflow python=3.6
3. activate tensorflow
4. conda install jupyter
5. jupyter notebook
6. launched Jupyter from icon

**Console Output:**

[I 08:25:00.485 NotebookApp] Serving notebooks from local directory: C:\Users\username
[I 08:25:00.485 NotebookApp] The Jupyter Notebook is running at:
[I 08:25:00.485 NotebookApp] http://localhost:8888/?token=894991242b49e938713e48b673f44f82c4fafa4b4b0d8867
[I 08:25:00.485 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:25:00.500 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/username/AppData/Roaming/jupyter/runtime/nbserver-6280-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=894991242b49e938713e48b673f44f82c4fafa4b4b0d8867
[I 08:29:08.545 NotebookApp] 302 GET /?token=894991242b49e938713e48b673f44f82c4fafa4b4b0d8867 (::1) 0.00ms
[I 08:29:32.278 NotebookApp] 302 GET /?token=894991242b49e938713e48b673f44f82c4fafa4b4b0d8867 (::1) 1.00ms
[I 08:30:54.927 NotebookApp] 302 GET /?token=894991242b49e938713e48b673f44f82c4fafa4b4b0d8867 (::1) 1.00ms
[I 08:31:28.555 NotebookApp] 302 GET /?token=894991242b49e938713e48b673f44f82c4fafa4b4b0d8867 (::1) 0.00ms
[I 08:31:56.160 NotebookApp] 302 GET /tree (::1) 0.00ms
[I 10:23:02.379 NotebookApp] 302 GET /tree (::1) 0.99ms

**Jupyter Configs:**

(tensorflow) C:\Users\username>jupyter --paths
config:
    C:\Users\username\.jupyter
    C:\Users\username\Miniconda3\envs\tensorflow\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\username\AppData\Roaming\jupyter
    C:\Users\username\Miniconda3\envs\tensorflow\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\username\AppData\Roaming\jupyter\runtime

(tensorflow) C:\Users\username>jupyter --version
4.4.0

**Packages installed:**

(tensorflow) C:\Users\username>pip list
Package             Version
------------------- --------
absl-py             0.7.1
astor               0.7.1
attrs               19.1.0
backcall            0.1.0
bleach              3.1.0
certifi             2019.3.9
chardet             3.0.4
colorama            0.4.1
cycler              0.10.0
decorator           4.4.0
defusedxml          0.5.0
entrypoints         0.3
gast                0.2.2
grpcio              1.19.0
h5py                2.9.0
idna                2.8
ipykernel           5.1.0
ipython             7.3.0
ipython-genutils    0.2.0
ipywidgets          7.4.2
jedi                0.13.3
Jinja2              2.10
jsonschema          3.0.1
jupyter             1.0.0
jupyter-client      5.2.4
jupyter-console     6.0.0
jupyter-core        4.4.0
Keras               2.2.4
Keras-Applications  1.0.7
Keras-Preprocessing 1.0.9
kiwisolver          1.0.1
lxml                4.3.2
Markdown            3.0.1
MarkupSafe          1.1.1
matplotlib          3.0.3
mistune             0.8.4
mkl-fft             1.0.10
mkl-random          1.0.2
nbconvert           5.4.1
nbformat            4.4.0
notebook            5.7.6
numpy               1.16.2
pandas              0.24.2
pandas-datareader   0.7.0
pandocfilters       1.4.2
parso               0.3.4
pickleshare         0.7.5
Pillow              5.4.1
pip                 19.0.3
prometheus-client   0.6.0
prompt-toolkit      2.0.9
protobuf            3.7.0
psutil              5.6.1
Pygments            2.3.1
pyparsing           2.3.1
pyrsistent          0.14.11
python-dateutil     2.8.0
pytz                2018.9
pywinpty            0.5.5
PyYAML              5.1
pyzmq               18.0.0
qtconsole           4.4.3
requests            2.21.0
scikit-learn        0.20.3
scipy               1.2.1
Send2Trash          1.5.0
setuptools          40.8.0
six                 1.12.0
sklearn             0.0
tensorboard         1.12.2
tensorflow          1.12.0
termcolor           1.1.0
terminado           0.8.1
testpath            0.4.2
tornado             6.0.1
traitlets           4.3.2
urllib3             1.24.1
wcwidth             0.1.7
webencodings        0.5.1
Werkzeug            0.15.0
wheel               0.33.1
widgetsnbextension  3.4.2
wincertstore        0.2
wrapt               1.11.1

(tensorflow) C:\Users\username>

**Comment by alifuk** [comment]
pip uninstall notebook
pip install notebook==5.7.5

**Comment by ciupicri** [comment]
Check in the browser (developer mode) if the MIME type of the Javascript files returned by the web server is correct, i.e. `application/javascript` and _not_ `text/javascript`.

Related issue: https://github.com/ContinuumIO/anaconda-issues/issues/10735

**Comment by ciupicri** [comment]
Also this seems to be a duplicate of issue #4491.

**Comment by kennanlau** [comment]
Problem solved by

1. pip uninstall notebook
2. pip install notebook==5.7.5
3. conda create --name tensorflow python=3.6
4. jupyter notebook

Kudos to both alifuk & ciupicri.

Thanks for the quick response.

**Comment by ciupicri** [comment]
Instead of a downgrade, you could also try [this workaround][1].

[1]: https://github.com/ContinuumIO/anaconda-issues/issues/10735#issuecomment-475099953

**Comment by fuaduae** [comment]
Hi, I am facing same problem.
My notebook is empty http://localhost:8888/tree
Does it mean that I lost all my files and folders?!!!

I did pip uninstall then install notebook but I am still getting the same empty page!
I finally uninstalled then installed Anaconda, but that didn't help either.

Any idea how to get back my notebook?
